### ISSUE TITLE
Allow expanded text to be defined by multiple chords (or a combination of chords and typing)

### ISSUE THREAD

**Issue by psoukie** [psoukie/zipchord#103]
This is based on the ideas in the discussion [Add Context Chording](https://github.com/psoukie/zipchord/discussions/101).

**Goals**

- [x] Allow dictionary definitions combining multiple chords, such as `tr fr    therefore` to be recognized, and to dynamically replace output (if needed) produced by the first chord(s) in the sequence (such as if there is a chord like `tr    tree`). 
- [x] Allow dictionary definitions combining chords and typed text, such as `mn 1 1    November`

**Comment by psoukie** [comment]
Depends on #126

**Comment by Nooby-001** [comment]
Related:
Can we get an option to set "combos"?
My idea, you have chords for `the (te)` and `house (ho)`
1 You set T+E for THE and add `*` (example) in your dictionary (the `*` tells the app that if there's a chord or AC in front to see the typed `t` as a `th` chord)
2 You press `tho` and get `The house`
3 Profit!
You could also set suffixes this way: ` fn ` (finish) + `;g* ` (ing) = `finishing`  
`fd+g` = Funding  
`t+fd+g` = The funding
`t+sh+g` = The Shining! 
The combos would work with chords and autocompletes (ACs) and only if the app detects them in front of behind. They would have to be typed in front or back to avoid activating an existing combo

Ideas for more combos:
M--* for "many" `m+yr` = Many years
N--* for "not" `n+ps` = Not possible 
D--* for "done" `ov+d` = Overdone

Caveat:
**If** this is possible there would have to be a new way to make up chords, `f+d+g` is doable for QWERTY but not for Colemak, `n+p+s` is kind of hard, a solution would be to set the keyboard with "modifiers" on one side and chords and ACs on the other and an easy mnemonic system or ~~an arpeggiate key like Plover: press SPACE, type `n+p+s` one by one, release SPACE~~(Nope, that would add typing and the idea here is to reduce typing)

Hope this helps!

**Comment by psoukie** [comment]
If I understand correctly, it would allow combinations that would not need to all be individually explicitly defined in the dictionary. 

So a bit like the existing prefixes and suffixes but being able to specify there are surrounding words/chords/spaces/punctuation as a required context.

It could be done as the next step once the basic support for this feature is in place.
