### ISSUE TITLE
Exiting zipchord

### ISSUE THREAD

**Issue by jsampson45** [psoukie/zipchord#11]
If I restart the computer (Windows 10) Zipchord continues to provide chords, although there is no access to the menu or to the addition of chords. Zipchord does not appear in the task manager nor as an icon. How can one clear Zipchord from the computer?

**Comment by psoukie** [comment]
Thank you for reporting this. I’m currently traveling back from a business trip, and will look at it as soon as I’m back. ZipChord / AutoHotkey shouldn’t reload on reboot, especially not without being visible in the task bar. Is there any other software for modifying the keyboard behavior? When this happens, does it expand a chord into a full word?

Pavel

On Dec 8, 2022, at 5:45 AM, jsampson45 ***@***.***> wrote:

﻿

If I restart the computer (Windows 10) Zipchord continues to provide chords, although there is no access to the menu or to the addition of chords. Zipchord does not appear in the task manager nor as an icon. How can one clear Zipchord from the computer?

**Comment by jsampson45** [comment]
I was running another Autohotkey program so Autohotkey may survive a reboot. It may not be Zipchord. I think if Autohotkey scripts are actively closed before shutting down the computer this may solve the problem. I need to experiment further. I find that while the Autohotkey script is (silently) running, " and @ are interchanged, which I expect has nothing to do with Zipchord. I should apologise for assuming that Zipchord was responsible.

**Comment by psoukie** [comment]
No problem, I appreciate you took the time to submit the reports!

I have been a bit detailed with my job but will update the app this weekend.

Pavel

On Dec 8, 2022, at 4:17 AM, jsampson45 ***@***.***> wrote:

﻿

I was running another Autohotkey program so Autohotkey may survive a reboot. It may not be Zipchord. I think if Autohotkey scripts are actively closed before shutting down the computer this may solve the problem. I need to experiment further. I find that while the Autohotkey script is (silently) running, " and @ are interchanged, which I expect has nothing to do with Zipchord. I should apologise for assuming that Zipchord was responsible.
