### ISSUE TITLE
Shift is not capitalizing chords when Auto-capitalization is Off

### ISSUE THREAD

**Issue by lmendez5** [psoukie/zipchord#110]
**Describe the bug**
Is not working... I tested it in a previous version and worked fine. 
![image](https://user-images.githubusercontent.com/95358420/211582213-fe36ea25-614b-4124-b261-d0d14bcadec3.png)

**Comment by lmendez5** [comment]
Hi! well, here is the log and the actual text is: `RG gracias correcto para`
I was checking the documentation but I notice it changed. With a previos version I tested the Shift+chord and I got `Gracias` the same word but capitalized. So, I hope this log help.

Please copy the actual text output of your typing below:
OUTPUT:

ZIPCHORD SETTINGS:
ZipChord v.2.0.0-beta
capitalization=1
chord_file=C:\Users\Luis Alberto\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\chords.txt
chording=4
chords_enabled=1
hints=2
input_delay=80
locale=Español
output_delay=0
preferences=0
shorthand_file=C:\Users\Luis Alberto\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\shorthands.txt
shorthands_enabled=1
spacing=0
LOCALE SETTINGS:
all=`1234567890-=qwertyuiop[]\asdfghjkl;'zxcvbnñm,./
capitalizing_plain=.
capitalizing_shift=1/
other_plain=[
other_shift=9,[
remove_space_plain=.,;'-/=\]
remove_space_shift=1/;'-.235678]=\
space_after_plain=.,;
space_after_shift=1/;

INPUT LOG:
Event	Timestamp	last_output	fixed_output	chord_buffer	chord	start
Interrupted
Interrupted
Interrupted
Interrupted
KeyDown ~+r	2348109	128	128		gr	0
KeyDown ~+g	2348109	1	128	r	gr	0
KeyUp	2348187	1	128	rg+	gr	2348109
/KeyUp-fixed	2348187	1	1		gr	0
KeyUp	2348234	1	1		gr	0
/KeyUp-fixed	2348234	1	1		gr	0
KeyDown ~ 	2351312	1	1		gr	0
KeyUp	2351390	2	1	 	gr	0
/KeyUp-fixed	2351390	2	2		gr	0
KeyDown ~+r	2352140	2	2		gr	0
KeyDown ~+g	2352140	1	2	r	gr	0
KeyUp	2352250	1	2	rg+	gr	2352140
/KeyUp-chord	2352250	1	2		gr	0
KeyUp	2352265	1	2		gr	0
Chord for:gracias	2352265	1	18		gr	0
OUTPUTTING	2352265	1	18		gr	0
/KeyUp-fixed	2352281	9	9		gr	0
KeyDown ~ 	2353171	9	9		gr	0
KeyUp	2353250	2	9	 	gr	0
/KeyUp-fixed	2353250	2	2		gr	0
KeyDown ~+o	2357218	2	2		gr	0
KeyDown ~+c	2357234	1	2	o	gr	0
KeyUp	2357375	1	2	oc+	gr	2357234
/KeyUp-chord	2357375	1	2		gr	0
KeyUp	2357406	1	2		gr	0
Chord for:correcto	2357406	1	18		co	0
OUTPUTTING	2357406	1	18		co	0
/KeyUp-fixed	2357421	9	9		co	0
KeyDown ~ 	2358765	9	9		co	0
KeyUp	2358843	2	9	 	co	0
/KeyUp-fixed	2358843	2	2		co	0
KeyDown ~p	2363859	2	2		co	0
KeyDown ~a	2363859	1	2	p	co	0
KeyUp	2364000	1	2	pa	co	2363859
/KeyUp-chord	2364000	1	2		co	0
KeyUp	2364000	1	2		co	0
Chord for:para	2364000	1	2		ap	0
OUTPUTTING	2364000	1	2		ap	0
/KeyUp-fixed	2364015	9	9		ap	0
Interrupted
Interrupted

**Comment by lmendez5** [comment]
Here is the test with over as a chord, I got `over over over`
Please copy the actual text output of your typing below:
OUTPUT:

ZIPCHORD SETTINGS:
ZipChord v.2.0.0-beta
capitalization=1
chord_file=C:\Users\Luis Alberto\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\chords.txt
chording=4
chords_enabled=1
hints=2
input_delay=80
locale=Español
output_delay=0
preferences=0
shorthand_file=C:\Users\Luis Alberto\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\shorthands.txt
shorthands_enabled=1
spacing=0
LOCALE SETTINGS:
all=`1234567890-=qwertyuiop[]\asdfghjkl;'zxcvbnñm,./
capitalizing_plain=.
capitalizing_shift=1/
other_plain=[
other_shift=9,[
remove_space_plain=.,;'-/=\]
remove_space_shift=1/;'-.235678]=\
space_after_plain=.,;
space_after_shift=1/;

INPUT LOG:
Event	Timestamp	last_output	fixed_output	chord_buffer	chord	start
Interrupted
KeyDown ~v	2957218	128	128		ov	0
KeyDown ~o	2957218	1	128	v	ov	0
KeyUp	2957375	1	128	vo	ov	2957218
/KeyUp-chord	2957375	1	128		ov	0
KeyUp	2957375	1	128		ov	0
Chord for:over	2957375	1	128		ov	0
OUTPUTTING	2957375	1	128		ov	0
/KeyUp-fixed	2957375	9	9		ov	0
KeyDown ~ 	2958531	9	9		ov	0
KeyUp	2958656	2	9	 	ov	0
/KeyUp-fixed	2958656	2	2		ov	0
KeyDown ~+v	2959203	2	2		ov	0
KeyDown ~+o	2959203	1	2	v	ov	0
KeyUp	2959343	1	2	vo+	ov	2959203
/KeyUp-chord	2959343	1	2		ov	0
KeyUp	2959359	1	2		ov	0
Chord for:over	2959359	1	18		ov	0
OUTPUTTING	2959359	1	18		ov	0
/KeyUp-fixed	2959375	9	9		ov	0
KeyDown ~ 	2959984	9	9		ov	0
KeyUp	2960078	2	9	 	ov	0
/KeyUp-fixed	2960078	2	2		ov	0
KeyDown ~+v	2960453	2	2		ov	0
KeyDown ~+o	2960453	1	2	v	ov	0
KeyUp	2960593	1	2	vo+	ov	2960453
/KeyUp-chord	2960593	1	2		ov	0
KeyUp	2960609	1	2		ov	0
Chord for:over	2960609	1	18		ov	0
OUTPUTTING	2960609	1	18		ov	0
/KeyUp-fixed	2960625	9	9		ov	0
Interrupted
Interrupted

**Comment by psoukie** [comment]
Tricky, but I finally see what went wrong! The chords typed with Shift do not get capitalized when the "Auto-capitalization" setting is "Off." (Internally, with the more flexible behavior that optinally allows Shift in chords, I relied on setting the flag to capitalize the upcoming chord when Shift is pressed. But that flag gets ignored if the Auto-capitalization setting is off.) Should be an easy fix.

**Comment by lmendez5** [comment]
Gracias!! Thank you... I change the Output settings to `For Shortcuts` and now is working fine... sorry if I misunderstood something, thank you for replying!

**Comment by psoukie** [comment]
It's definitely a bug. The Shift key should capitalize the chord regardless of the Auto-capitalization setting. I'll fix it tonight after work.

**Comment by psoukie** [comment]
This should be fixed in [Release Candidate 2](https://github.com/psoukie/zipchord/releases/tag/2.0.0-rc.2).
