### ISSUE TITLE
Case to help tuning chord triggering

### ISSUE THREAD

**Issue by lmendez5** [psoukie/zipchord#117]
I notice that in a random way typing with no chords is casting a chord. I logged this behavior with this test text `si se tiene para sin embargo, es algo para si sin embargo, 
es en donde en si no ` the chord is the combination `si = sin embargo,` and in the former text I never intended that chord. As you can notice, there are a "si" word successfully typed, but there are two "sin embargo," instead two "si" alone.

[debug.txt](https://github.com/psoukie/zipchord/files/10393923/debug.txt)

**Comment by psoukie** [comment]
I'm going to close this as "Won't fix" but will keep an eye on ways to make the detection even smarter about these edge cases.
