### ISSUE TITLE
Changing font color of hints does not work on 2.0.0-rc1

### ISSUE THREAD

**Issue by ellieLitwack** [psoukie/zipchord#118]
**Describe the bug**
- Changing the font color of the hints does not work.
- Expected behavior is that the font color box will accept a hex code that sets the font color. Actual behavior is that, once the font color is changed, the hints turn black with a colored outline. 

**Useful Details**
Even if you restart zipchord or change the settings back to the original color, the issue persists, as shown in the images below. Here are two images to demonstrate.

![image](https://user-images.githubusercontent.com/19858659/211866215-3e8416d9-e5e8-45ba-82d5-76bcddbb618b.png)

![image](https://user-images.githubusercontent.com/19858659/211865820-e9bc2591-b69e-42e9-a376-3abc5c003e6d.png)

I am running windows 10.0.19044 Build 19044.

P.S.: 2.0 is a game changer! Love the improved chord detection.

**Comment by psoukie** [comment]
Thank you. As a workaround, please try without the leading "#". I made a mental note to come back and add code to allow "ff0000" as well as "#ff0000" and show error if an incorrect color code is entered, but haven't done it. (Similar for the other number fields that should give an error if it's not a number.)

Thank you for the report!

**Comment by psoukie** [comment]
This should be fixed in [Release Candidate 2](https://github.com/psoukie/zipchord/releases/tag/2.0.0-rc.2).
