### ISSUE TITLE
Home-made dictionaries

### ISSUE THREAD

**Issue by jsampson45** [psoukie/zipchord#12]
If one tries to load a dictionary which has many chords that are anagrams of each other, error messages appear with no opportunity to abort the loading. One has to use the task manager to close Zipchord. Before restarting it is necessary to cut or delete the dictionary to stop Zipchord resuming the error messages.

**Comment by psoukie** [comment]
Thank you for the report! The behavior has been that ZipChord gives an error message for each invalid or duplicate entry in the dictionary. I added a dialog option that asks after encountering the first error whether to continue loading the dictionary. That can be useful to list all the problems and allows the rest of the valid entries to load, but I understand it can be very unhelpful if there are many duplicates. So after seeing the first error, you can just say "No" and stop loading the rest of the dictionary.

The [fixed version](https://github.com/psoukie/zipchord/blob/updates/source/zipchord.ahk) is in the "updates" branch, and I hope to combine it with other fixes and release hopefully still today.
