### ISSUE TITLE
Ignore chords in the middle of a word

### ISSUE THREAD

**Issue by psoukie** [psoukie/zipchord#13]
thank you! It works pretty well! here is a little test: 

![image](https://user-images.githubusercontent.com/95358420/203443731-469af77e-4912-41ba-a256-4047cfa85889.png)

There is something could be an improvement, is about fast typing triggering a chord between the word is being typed. Maybe if the chord could be able to detect if there is an space before it, else is not a desired chord. For instance, I am typing the word `centena` but I have the chord `ent=entonces` so the script is triggering `c entonces ena`. Tell me if make sense to you, or maybe it happens to you as well. 

This script is a great partner alongside keyboard and mouse customization!
very nice work! 🤝

_Originally posted by @lmendez5 in https://github.com/psoukie/zipchord/issues/9#issuecomment-1324391446_

**Comment by psoukie** [comment]
I'm planning on implementing this, with the modification that suffixes will still be detected and allowed while a word is being typed, but other chords will be ignored. (By consistently using an infrequent key to include in "suffix" words, such as ";" or "'", the risk of accidental triggers will be minimal.

**Comment by psoukie** [comment]
I took advantage of being sick for a few days -- but not too sick to prevent me from coding. The new pre-release [version 1.8](https://github.com/psoukie/zipchord/releases/tag/v.1.8.0) has a lot of the things I had been planning. See the release notes in the link, and also [updated documentation](https://github.com/psoukie/zipchord/tree/refactor-shift#readme) for that version.

This ended up being a complete rewrite of ZipChord, but in return, there is now a "Restrict chords while typing option" which does what's described above based on spaces, Enter, cursor movements, and predefined (and soon-to-be-customizable) punctuation. 

Plus, Shift can now either work as normal Shift (to capitalize the chord, which it could not before), or as a separate key for the chord -- just like space bar and regular keys could do until now. By checking the "Allow Shift in chords" option, you can start defining chords that include Shift (represented by `+` in the chord definitions).

This new version should also not suffer from the bug with capitalization in the `is:unread`. 

I expect there are new bugs, so if you find any, please open a new issue to let me know.

**Comment by psoukie** [comment]
Quick additional question on this:  Should ZipChord allow a chord to be followed by a chord even in restricted mode?

I am assuming there are only three scenarios after a user enters a chord on purpose (if they are not using smart spaces "after chords"):
1. They manually type a space (or punctuation) to continue typing.
2. They press a chord for the next word (and expect a "before chord" smart space to be printed before the word).
3. They add a suffix either by (a) using a chord, or (b) regular typing.

Based on this, I think the only scenario in which a chord could be potentially triggered by mistake is 3.b. -- by starting a manually typed suffix after the chord. In all other scenarios, it seems there is no harm and some benefit in having the chord being recognized -- i.e. to allow two chords to follow each other.

Please let me know what you think about this.

**Comment by lmendez5** [comment]
I agree with you, these three scenarios you proposed are ok for regular usage. If you let me think a little further (because is our case) I am using some chords for for coding in java or queries in SQL, where is ok for sending chording in a row for variables, methods, etc. But, as I said, is not for regular typing, but it could be a 4th scenario in case you consider it a valid one, and add another checkbox at the configuration panel allowing this kind of usage. Indeed, in future could be a nice feature adding application recognition and the script could behaves according to the current app. Like my mouse ([Logitech G600](https://www.logitechg.com/en-us/products/gaming-mice/g600-mmo-gaming-mouse.910-002864.html)), it is able to handle a different configuration depending the current app.
Out of this special case... you are right!

**Comment by psoukie** [comment]
The ability to switch based on active window is now also implemented.
