### ISSUE TITLE
Make OSD Relative To Active Screen

### ISSUE THREAD

**Issue by Danc2050** [psoukie/zipchord#134]
**Is your feature request related to a problem? If so, please describe.**
No

**Describe the solution or functionality you'd like**
I use a quad-monitor setup and a nice feature for those that use the OSD hints, would be if the OSD displayed on their active window.

**Additional context**
Currently I'm just using the tooltip and I think I prefer that ATM, but just logging this idea for those that want to have the hint be on a focused focused screen.

[Some popular AHK code that deals with getting multiple monitor data](https://www.autohotkey.com/boards/viewtopic.php?f=6&t=4606).

**Comment by Danc2050** [comment]
Also, if you'd rather these types of things be a discussion, I can do that. I realize now that maybe putting these as Issues makes it look bad since newcomers will think the project has a bunch of issues, when in fact it's a lot more developed than some paid solutions with some enviable features.

You can feel free to delete this (and others) and redirect me to open up a discussion instead.

**Comment by psoukie** [comment]
> Also, if you'd rather these types of things be a discussion, I can do that.

This is actually better for me to keep track of as a work item because it is an enhancement I'd like to implement. I hope as long as people don't see many issues labeled as "bug", they shouldn't be scared. (I can move or convert things that are different.)

**Comment by psoukie** [comment]
I ended up combining a few ideas from this and another thread. Thank you!
