### ISSUE TITLE
2.0.1 Bugs

### ISSUE THREAD

**Issue by Nooby-001** [psoukie/zipchord#144]
- Still flagged as virus, 13 flags now.
For noobies like me: the app's made with AutoHotkey and that software has a false-positive problem 👉[Link](https://www.autohotkey.com/boards/viewtopic.php?t=90504) 
AutoHotkey 1.2 gets detected twice, 2.0 gets detected 8 times.
So far none of the Zipchord versions has made changes to my PC (I check my task manager for RAM hogs) and It has never tried to call home (Comodo Firewall)
 You can also read the Source Code file, I took a look because:
- Zipchord scanned my computer!! (Kidding)
I downloaded 2.0.1 to my Downloads folder, after Avast did its "this looks suspicious" dance I start Zipchord and WTH?? It already has my custom dictionaries set! Did it scan my PC? How did it find my dictionaries folder in another directory??
So I read the Source Code file and, for what I understood, Zipchord sets a registry key with the location of the last used dictionaries. I'm ok with that but could we get a Read Me text with important info like that for us chickens?
- Trouble with hints
It takes some tries for the hints to show, even with "frequency" on Always. Autocompletes never show on the tooltip. 
- Autocompletes don't work sometimes
I only have three ACs, (haven't started my dictionary)
 cus	customer
cust	customer service
cutt	cutting board
None of them work on Notepad if they're the first word in the first line, they also may or may not work after that, here's a sample: 
cutt cutting board cutt cutt customer cus customer customer cutting board customer service 

Changed my detection delay from 80 to 160 and that helped the ACs but now the chords aren't working, sample: 
cutt cutting board cutting board cutting board cus customer service customer customer customer service thththth thhtthth (the)

I also tried on Firefox and Email and same thing. 

Hope this helps!

**Comment by psoukie** [comment]
For the security -- good point, I'll make sure I will list all the things ZipChord does in terms of storing its settings or looking for its dictionaries. 

For the hints and shorthands -- I know this is frustrating but I could not reproduce the issue. For hints and shorthands, there is a "by design" behavior where you need to type a space, Enter or punctuation before that word (otherwise, ZipChord doesn't know you didn't e.g. click the mouse into a middle of a word). But other than that, I am getting suggestions for both chords and shorthands in both tooltips and OSD. I'll post some instructions tomorrow on how you could try to debug or isolate the issue.

You also should not need to have the delay setting at that high, because it makes chording harder. The ability to detect and expand shorthands is unrelated. As I wrote, I'll post more details to see if we can do gyre out why you're experiencing these issues.

**Comment by psoukie** [comment]
Off topic: I posted a result of an interesting experiment in the #131 issue.

For figuring out what might be wrong with the shortcuts not being recognized: Could you please try to do the following steps? 

1. Download the zipchord-dev version under the [latest release](https://github.com/psoukie/zipchord/releases/tag/2.1.0-beta)
2. On the About tab of this version, check the "Log this session (debugging)" option. 
3. Type some short text in the application where you experience the problem.
4. Re-open the ZipChord window. This will stop the debugging and will open a text file with the debug information.

If you could attach the debug file here, I'm going to see what might be going causing the issue.

**Comment by Nooby-001** [comment]
Been kinda busy but I'll make some time on Sunday and run some tests.
A quick test right now: 
👉bu building customer 👉cust customer service building building 👉cust customer service 👉cust customer service
I do get the OSD now most of the time, nothing happens on the Firefox search bar until the second or third try.

**Comment by Danc2050** [comment]
I wouldn't call it a bug, 'cause it's not your fault, just crazy Antivirus program heuristics I think (I set mine pretty high from what I recall). Here is an image just for reference:
![image](https://user-images.githubusercontent.com/32185616/216233981-a17f9e4b-4b7f-4f5c-8ae5-848fd1efd6ee.png)

**Comment by psoukie** [comment]
I'm not surprised. I wanted to create my own installer, so I'd know exactly what it does during installation and uninstallation, but requesting admin access to add things to Program Files and cleaning up its own files (including the file that is doing the uninstallation), can definitely raise flags.

Maybe I'll consider a third party installer instead. The good news is that the ZipChord exe in Beta 2 was getting less false positives when I checked.
