### ISSUE TITLE
Shorthand Does Not Work If Backspace Is pressed

### ISSUE THREAD

**Issue by Danc2050** [psoukie/zipchord#159]
**Describe the bug**
- **Expected** 
Shorthands are tolerant of user error (such as backspace).
- **Actual**
Shorthands are **not** tolerant of user error (such as backspace).

IMO also `enter`/`return` would be nice to expand a chord and if a user went backwards without typing anything, then it may be nice to clear the `enter`/`return` form the buffer (who knows, maybe users hit enter by accident). 

**Useful Details**
- Which settings do you have selected in the ZipChord settings?
A: Use Shorthands
- If the output is wrong, what is the sequence of keys pressed, the dictionary entry, and what text appears on the screen?
A:  If I type a simple shorthand form the dictionary (e. g., `tht`), but when I type `th` and then backspace `t`, then retype `ht` (`tht`) followed by space (or if auto expand is selected, no space), the shorthand fails to expand. It seems backspaces clear the buffer (not sure how this is implemented) unnecessarily or beyond some point where it doesn't recognize they shorthand anymore perhaps. 

**Possible Related Issue**
This could be what the person in #142 was experiencing.

**Comment by Danc2050** [comment]
I did a little logging with `MsgBox` and when I do the above example, example, i get this:
![image](https://user-images.githubusercontent.com/32185616/222929568-1b710072-95e9-4001-a808-fafc16670197.png)

These lines seem to be the offender: 
```
        if (last_output & OUT_INTERRUPTED & ~OUT_AUTOMATIC)
            shorthand_buffer := "<<SHORTHAND_BLOCKED>>"         
```
I'm sure there is a reason for this, but maybe I will not run into it... for now I commented out the line and replaced it with this `shorthand_buffer := SubStr(shorthand_buffer, 1, StrLen(shorthand_buffer)-1)`, which works for backspaces.

BTW, I hope you and your son are in good health!

**Comment by psoukie** [comment]
Thank you, the last few weeks were a combination of finishing an urgent project for work and now Im spending the weekend with my kids. Thank you for ch Ching, things are on the right track now!

For the backspace: indeed, the reason the shorthands have been disabled when a user presses Backspace was that it had been leading to many inadvertent text expansions. But with the new engine in beta, this should be possible to do in a better way.

I just had to take a break from it to work on other things but am planning to resume by next weekend!

**Comment by Danc2050** [comment]
I am glad to hear you are okay and things are getting better!!!  I hope I speak for the rest of us here that we truly value your work, but also understand you do this all free and also have a life to live. Thank you for all you do inside and outside of Zipchord 🙏.

**Comment by Danc2050** [comment]
related: shorthands do not seem to work  on the first  line  when typing on https://charatyping.com/, but chords do.

**Comment by ethanGoold** [comment]
I would also love to see this change. I am having a seemingly related issue where I can't use shorthands for the first word of a new file or new web page. They work for all subsequent words.

**Comment by psoukie** [comment]
I'm resuming work on this. These are indeed two separate items:
- An enhancement to track Backspace and apply shorthands correctly. (On my roadmap)
- Ability to expand shorthands when you start typing somewhere. This one is blocked by design because in situations where the caret position is unknown, it is often because the user mouse clicks on navigates with arrows to edit existing text. In those situations, it was frustrating when such typing got interpreted as a shorthand.  I don't, know of a solution to this, so the shorthands are ignored. (Somewhat related, it would also be better -- and more consistent -- to ignore smart spacing in the same situations because currently, e.g. adding a comma into a sentence after moving the caret adds an extra space).

**Comment by psoukie** [comment]
Version 2.3.0 addresses both behaviors -- Backspace and a workaround by re-enabling shorthands with Shift after moving a caret.
