### ISSUE TITLE
Allow Immidiate Chord entry after auto deletion of mistyped chords. 

### ISSUE THREAD

**Issue by KennethRamsey** [psoukie/zipchord#168]
I like chords and i like the setting of "Delete mistyped chords".  Whenever i mistype a chord and it's auto deleted, i want to immediately press the correct chord that i was intending to type, but for some reason no chords at all are registered after the auto deletion has taken place. 

To show an example,  if i want to type the chord for "about", and i accidentally mistype and press "av", it auto deletes the bad chord which is great, but then i will immediately type the chord "ab", and it never expands into the word about.  To have chords start working again i have to push space, but then i have to delete that extra space, and all of this extra typing unfortunately negates all the time that could been gained from this wonderful feature. 

Could you update the setting of "Delete mistyped chords" so that chords will still register after an auto chord deletion has taken place?  Or perhaps you could  make this a sub setting of the above mentioned setting, something like "allow immediate chord entry after mistyped chord deletion". Thank you!

**Comment by psoukie** [comment]
Thank you for reporting this! (I don't use the 'Delete typed chords' option normally so wasn't aware of how this did not play nice with the "Restrict chords while typing" option.) It should work correctly now.
