### ISSUE TITLE
Duplicate Alt (letter) shortcuts on settings buttons

### ISSUE THREAD

**Issue by duianto** [psoukie/zipchord#171]
**Describe the bug**

There are duplicate Alt (letter) shortcuts on the buttons in the ZipChord settings window.

In the Chord dictionary section:
The `O` on the Open button is underlined
And the `o` on the Reload button is underlined.
This prevents reloading the chords list with an Alt (letter) shortcut.

The `E` on the Edit button is underlined in the Chord dictionary section.
And the `e` on the Open button is underlined in the Shorthand dictionary section.
This prevents opening a shorthand dictionary from an Alt (letter) shortcut.

### Expected

`r` isn't underlined on any button, maybe it could be used for the Reload Chord dictionary button.
And `n` seems to be available for the Open Shorthand dictionary button.

#### 2.2.0-alpha

![AutoHotkeyU64_5ajd0QRaOG](https://github.com/psoukie/zipchord/assets/13420573/5b67655c-5bc2-470e-a1d9-a6c3f34557cc)

#### 2.1.2

![zipchord_OZTtpwdf0e](https://github.com/psoukie/zipchord/assets/13420573/699659f9-3990-4452-9ac3-680bb7cc7266)

**Comment by psoukie** [comment]
Given that I teach localization students about avoiding duplicate shortcuts like this, this is embarrassing. Thanks for reporting it. I'll fix it in an update.
