### ISSUE TITLE
Add Shortcut window, Ctrl Backspace adds a tall rectangle symbol

### ISSUE THREAD

**Issue by duianto** [psoukie/zipchord#172]
**Describe the bug**

`Ctrl Backspace` adds a tall rectangle symbol, in the Add Shortcut window.

### Reproduction steps

- In a text editor type: `asdf`
- Select the letters: `asdf`
- Hold `Ctrl c`, until the Add Shortcut window appears
- In the Chord input box, type: `asdf`
- Press `Ctrl Backspace`

### Expected

It should erase the previous word.

### Observed
A tall rectangle symbol appears after the letters: `asdf`
(the tall rectangle symbol looks like two spaces while typing this message in the GitHub Write tab. But on the GitHub Preview tab (and possibly when this is posted) it appears as a rotated square with a question mark).

It happens in both 2.2.0-alpha and 2.1.2
(screenshot from 2.2.0-alpha)

![AutoHotkeyU64_8YRNAwMpDB](https://github.com/psoukie/zipchord/assets/13420573/cefe910e-b80b-4c79-a595-f83a1611b00c)

### Notes

It doesn't seem to be limited to ZipChord, because the same thing happens when renaming a file in Windows File Explorer.

![explorer_24atJZuaPu](https://github.com/psoukie/zipchord/assets/13420573/824ba6cd-8ac0-4331-a9bf-9bc963ea9be5)

### System

Windows 10 22H2

**Comment by psoukie** [comment]
Unfortunately, this is external -- coming from the Windows system UI available through AutoHotkey. There is a workaround for this I could implement -- by conditionally overriding the Ctrl-Backspace keyboard shortcut when a ZipChord dialog box is open to send a combination like Ctrl+Shift+Left and then Delete. But that's not super clean.

Please let me know if this is a scenario you run into a lot, and would like the Ctrl-Del workaround.

**Comment by duianto** [comment]
It's probably better to have the workaround because new users will keep encountering the issue.
And frequent users will add a new chords, less often each time.
Eventually, they will forget that `ctrl backspace` doesn't work here.
