### ISSUE TITLE
2.2.0-alpha, Two "IO Representation error" dialog boxes when pressing ;g

### ISSUE THREAD

**Issue by duianto** [psoukie/zipchord#173]
**Describe the bug**

In 2.2.0-alpha, pressing `g;` after a chorded word, shows two error dialog boxes, 
one after the other, with only one word, changed "combining" or "getting".
- "IO Representation error: Requested combining chunks that exceed the length of _sequence," 

![AutoHotkeyU64_BodclfqjV9](https://github.com/psoukie/zipchord/assets/13420573/984a0054-9713-450c-8b84-3857ffb59f6c)

- "IO Representation error: Requested getting chunks that exceed the length of _sequence,"

![AutoHotkeyU64_HBlpfVzt72](https://github.com/psoukie/zipchord/assets/13420573/f2f46a4f-d9a8-47f0-aae6-fadd74da9fbb)

**Reproduction steps**

- In notepad, press both letter keys: `be`, it types: `be |` (`|` (vertical bar) is the cursor)
- type `g;`

**In 2.1.2**
It works as expected, and the line changes to: `being |`

**In 2.2.0-alpha**
It shows the two error dialog boxes "IO Representation error".
When both dialogs are closed, then the line changed to: `be ;ing1 |`

I noticed that the `chords-en-starting.txt` list has some chords with a second definition that includes `;g`.
For example:
```
hv	have
hv ;g	having
```
and it works as expected, `hv` types `have `
and `;g` changes it to `having |`.

If the expectation is that `ing` modified chords should be added manually.
Then the error dialog should have a descriptive message.

**Note**
2.1.2, might not support the second `;g` version of the chord. 
Because with the same starting chords list that includes `hv` and `hv ;g`. 
Typing `hv ;g` results in: `haveing |`

**Comment by psoukie** [comment]
Fixed in [version 2.2](https://github.com/psoukie/zipchord/releases/tag/2.2.0)
