### ISSUE TITLE
Escape keys for curly brackets.

### ISSUE THREAD

**Issue by uraniumcrystalsmaster** [psoukie/zipchord#176]
**Is your feature request related to a problem? If so, please describe.**
I can't figure out a way to use curly brackets for my chord definitions. 

Example definition:
def _calcMeshVolume(T mesh){ {enter}//code not included for demonstration {enter}} 

Example output:
def _calcMeshVolume(T mesh){ 
//code not included for demonstration 
} 

**Describe the solution or functionality you'd like**
Add escape keys functionality to bypass curly bracket functions, but display curly brackets between them. 

Example definition with escape key open "&~" and escape key close "~&":
def _calcMeshVolume(T mesh)&~{~& {enter}//code not included for demonstration {enter}&~}~& 

Example output:
def _calcMeshVolume(T mesh){
//code not included for demonstration 
}

**Comment by psoukie** [comment]
The `{` and `}` characters are special in AutoHotkey, so they need to be escaped as e.g. `{{}`. The following entry in the chord dictionary will work: 
```
msh	def _calcMeshVolume(T mesh){{} {Enter}//code not included for demonstration {Enter}{}}
```
