### ISSUE TITLE
Google Drive Saying "zipchord-install-2.4.0.zip" is infected with a virus

### ISSUE THREAD

**Issue by Hardy02** [psoukie/zipchord#210]
Hello All,

I uploaded ZipChord to google drive to download on another computer that has no access to GitHub due to an internet filter.

When I go to download, google drive pops up the attached notification.

Is it correct? Why is it saying this?
![17195383499101237883681812990721](https://github.com/psoukie/zipchord/assets/44354333/f104fc8b-f6c4-498f-aef4-92c858d679e3)

**Comment by psoukie** [comment]
A false positive detection by antivirus programs has come up from time to time. I was searching for a Google page that would allow me submit the file for review and alert them to the error in the detection (similar to what you can do with Microsoft, which I had done a few times in the past when Microsoft would incorrectly report ZipChord as a virus), but I could not find one.

Please see under https://github.com/psoukie/zipchord/wiki/Privacy for a brief explanation of what exactly ZipChord does and does not do, and for why from time to time antivirus software incorrectly flags it. 

If anyone finds a resource where Google allows reporting of false positive and submission for deeper review, let me know.
