### ISSUE TITLE
Ctrl+C shortcut broken

### ISSUE THREAD

**Issue by kurushimee** [psoukie/zipchord#214]
**Describe the bug**
- Upon activating the shortcut, two windows for Add Shortcut open, one with no text selected, and one containing the word that was selected.
- If you select a word and press the shortcut to Add Shortcut, it creates two windows. Trying to add a chord through the window that has the selected word results in an error `The chord for '' needs to be at least two characters.` and trying to press the "Close" button on the window with the word closes the other window instead, and results in an error without closing this window:
```
Error: Invalid Gui name.

Specifically: 0xc0552:Destroy

              Line#
--->       108: Gui,%window_handle%:Destroy

The current thread will exit.
```
Pressing the "Close" button further after the window without the selected word has been closed does nothing but output the error,  and trying to close the window manually via the window controls results in the same error, but closes the window.

![image](https://github.com/user-attachments/assets/d10571d4-83cf-45dd-b6d9-b1b9c3932ebd)

**Useful Details**
- Default ZipChord settings, available upon installation.
- The appearance of this bug seems to be influenced by how long the Ctrl+C shortcut is pressed for.

**Comment by psoukie** [comment]
Thanks, @kurushimee! The Add Shortcut window should now simply refocus if the Add Shortcut feature is triggered again by the keyboard shortcut or from the tray icon.
