### ISSUE TITLE
Holding down shift may cause a warning

### ISSUE THREAD

**Issue by kurushimee** [psoukie/zipchord#216]
**Describe the bug**
- A window like this appears:
![image](https://github.com/user-attachments/assets/8dc6807e-8743-4fb9-8581-d307a04d7202)
- Sometimes, when not inputting any chords/shorthands and just holding down shift for a little time, the window as shown above may appear. Pressing "Yes" closes this window and nothing else happens, everything continues to work normally.

**Useful Details**
- Default settings, but detection time is on 100ms and smart spaces after punctuation turned off.
- I can't find an exact pattern as to how this gets triggered, and I'm not sure if it's limited to holding down just shift.

**Comment by psoukie** [comment]
Thank you for reporting this including the details. This warning should be fixed now.
