### ISSUE TITLE
Have to press spacebar twice when smart spaces after chord is not selected

### ISSUE THREAD

**Issue by lmendez5** [psoukie/zipchord#25]
Describe the bug
- Pressing the chord keys the output is ok, but to keep typing a space is required (as normal) but the space is deleted and have to press spacebar twice

Useful Details
 ![image](https://user-images.githubusercontent.com/95358420/208140934-a3709401-23a8-405b-b691-d8ea31da65c2.png)

**Comment by psoukie** [comment]
I overlooked to retest this scenario after tweaking the bitwise logic for the existing output.
This should now be fixed in [1.8.1](https://github.com/psoukie/zipchord/releases/tag/v.1.8.1)
