### ISSUE TITLE
Ability to edit the last executed chord

### ISSUE THREAD

**Issue by dzeruel** [psoukie/zipchord#34]
**Describe the solution or functionality you'd like**
It would be nice to edit the last chord that was executed. Sometimes a certian chord triggers too many times and quick adjustments like this would be beneficial.

**Comment by psoukie** [comment]
Thank you for the suggestion. So a keyboard shortcut that would undo the last chord? What would be the ideal way this would work?

**Comment by psoukie** [comment]
I forgot to say, there is also an option in the menu for "Delete mistyped chords" -- this automatically undoes chords that do not exist. I noticed this morning that this feature wasn't working correctly, so I fixed it in the [latest release](https://github.com/psoukie/zipchord/releases). 

But I assume this is different from what you originally suggested, so please let me know what behavior or ability you'd like to see to edit / remove the last chord.

**Comment by psoukie** [comment]
You can also undo the last automated chord with Ctrl+Z (Undo).
If a chord triggers too many times, you could increase the "Detection delay" setting. 

Please let me know if you are still experiencing issues with this.
