### ISSUE TITLE
Error: "'" is not a valid key name

### ISSUE THREAD

**Issue by nightscape** [psoukie/zipchord#4]
Hi @psoukie, I was looking for a chording solution for a long time until I found this gem!
Unfortunately, I'm getting the following error right from the start:
![image](https://user-images.githubusercontent.com/35170/190409835-a41f9534-a847-46fb-9722-da4647b7a9b9.png)

Have you ever encountered that or any idea how to handle it?
One thing worth mentioning, is that I use a special keyboard layout (BONE, a derivation of NEO), created using [KbdEdit](http://kbdedit.com/). Could this have sth. to do with it?

Btw, have you seen the [CharaChorder](https://www.charachorder.com/) devices? They do the same thing on a hardware level.

**Comment by psoukie** [comment]
Sorry for the late reply. No, I have not encountered this before. If I understand correctly, when you download the app and run it for the first time, this is the error you receive (without any typing)? A special keyboard layout should not play a role in this (I am using one myself, even though embedded in the keyboard firmware). Let me investigate a bit if I can guess from the line number and error message what could be going on.

**Comment by nightscape** [comment]
Hi @psoukie, thanks for getting back to me 👍 
Yes, this was the absolute first thing I encountered when launching the app.
Hardware vs. software layouts might make a difference, as I assume the keyboard firmware directly sends modified key codes, which to the OS should be completely transparent.

**Comment by psoukie** [comment]
Can you try please try the attached version and let me know if it gives the same or different error on your machine?

[zipchord-test.zip](https://github.com/psoukie/zipchord/files/9643403/zipchord-test.zip)

**Comment by nightscape** [comment]
Yes, although now it is in line `077`. The rest is identical.
One thing to note is that ZipChord continues running afterwards, but it doesn't seem to do anything.
I have a single chord `dm` which expands to `demo`, but I can simultaneously press the two keys as much as I want and it doesn't expand anything.
@psoukie thanks a lot for your investigation!

**Comment by psoukie** [comment]
Thank you,

One clarification, is the error message exactly the same, including by the

"'" is not a valid key name

part? Or is there a different character between the quotation marks?

Pavel

On Sep 26, 2022, at 12:46 AM, Martin Mauch ***@***.***> wrote:

﻿

Yes, although now it is in line 077. The rest is identical.
One thing to note is that ZipChord continues running afterwards, but it doesn't seem to do anything.
I have a single chord dm which expands to demo, but I can simultaneously press the two keys as much as I want and it doesn't expand anything.
@psoukie<https://github.com/psoukie> thanks a lot for your investigation!

**Comment by nightscape** [comment]
Oh, you're right, I missed that!
Now it's actually `"=" is not a valid key name.`

**Comment by nightscape** [comment]
I just removed all keyboard layouts except the default one, and now the error is gone and ZipChord works correctly.
I'll do some research to find out if there are know issues with AHK and alternative keyboard layouts.

**Comment by psoukie** [comment]
Thank you for updating me on this!
It does look like something that is happening upstreams – in terms of how KbdEdit and AHK interact. So unfortunately it is outside of what I can do (or work around) within my tool.
I'm going to close this as Won't Fix (well, External, really, but I don't see that option in GitHub), but please let me know about anything else you find out.

**Comment by psoukie** [comment]
External. (Conflict between KbdEdit and AutoHotkey)
