### ISSUE TITLE
Smart capitalization doesn't work at the start of the text

### ISSUE THREAD

**Issue by YamikoHikari** [psoukie/zipchord#5]
Hey!
First, just want to quickly mention that I found your project since I am interested in stenography but was looking for something easier and more practical (for a normal user). This seems to be it and I am really excited for this project and I think I will be following your updates! :)
I have tried it out today, and I am already experimenting with different chords and also the sensitivity. 

### **Issue:**
That said, I have encountered a small problem - smart punctuation works somewhat unreliably. It doesn't capitalize chords at the start of text (if there's no dot before it), and sometimes adds a space before the word. I suppose this issue could be not easy to solve though since you would somehow need to check whether it's the start of the text field or something like that. However, I believe this is quite an important feature since capitalizing the chorded word manually instead is just too inconvenient.

### **P.S.**
Anyway, so far this is the only issue that makes the experience a bit unreliable and inconvenient, but really it's not a problem. Mostly I just wanted to greet you, express my interest in the project and share my experience so far (which other than this issue is really nice!) (And I don't know how else to contact you, since I've never really used twitter)

**Comment by psoukie** [comment]
Thank you, Yamiko!

I have added a feature where by pressing (and releasing) Shift key prior to using a chord, the first letter gets capitalized. 
I know it's not ideal, but the way ZipChord was created, combining Shift with chords is not as easy to implement.

I also think I fixed the situation where a space is incorrectly added at the start sometimes.

Thank you for letting me know about these, and I hope the new version works well for you! https://github.com/psoukie/zipchord/releases/tag/v.1.5.2

**Comment by YamikoHikari** [comment]
Thank you for the reply and the update, Pavel! (or do you prefer "psoukie"?)

I am checking the update and it's quite nice. I do seem to not get the unnecessary spaces at the start anymore.

As for the Shift capitalization feature, I can definitely see how it can be difficult to implement it. I've done quite some programming, including in AHK. Maybe at some point I can analyze your code and contribute to the project, though not sure at all. So far having this implementation of capitalization is nice, in fact perhaps it is ideal after all, at least for complex chords where additionally holding Shift for the whole duration of the chord would be too difficult. I will try to get accustomed with this implementation for now :)

**Comment by psoukie** [comment]
Proper Shift behavior is now fully implemented in the [1.8 release](https://github.com/psoukie/zipchord/releases/tag/v.1.8.0).

As a result, I removed the workaround with brief press of Shift. (At least unless people want to bring it back.)
