### ISSUE TITLE
Shorthands Implementation

### ISSUE THREAD

**Issue by psoukie** [psoukie/zipchord#52]
This issue tracks implementation of #47 

### Needed Features
- [x] Recognize and replace typed text shortcuts
- [x] UI support for selecting and editing the shorthands file
- [x] Chords and shorthands can be independently turned on and off
- [x] Enable auto-capitalization when using shorthands
- [x] Allow typing prefixes and suffixes with shorthands
-  ~~Use OpeningSpace and create EndingSpace() to make behavior consistent with chords~~ <ins>Not implemented because it did not make sense for shorthands</ins> 
- [x] Observe output delay for shorthands
- [x] Add detection option for shorthands to fire without space or punctuation
- [x] Check for duplicate shorthands in a dictionary
- [x] #79
- [x] Build default shorthands dictionary from the most frequent 5,000 English words

In the future, it would be good to also:
- Enable support for dead keys in shorthands. (It's still possible to create shorthands, just skip the dead keys in the shortcut definition.)
- Allow (some?) punctuation in a shorthand shortcut for affixes

**Comment by maxultimus** [comment]
"Build default shorthands dictionary with most frequent 5,000 English words"
Does it contain duplicates? ->https://github.com/psoukie/zipchord/issues/56

**Comment by psoukie** [comment]
> "Build default shorthands dictionary with most frequent 5,000 English words" Does it contain duplicates? ->#56

No, there should not be duplicates. There was a bug in Alpha 1 when opening the shorthands dictionary. Alpha 2 does not check for / warn about duplicates yet. But that should be a simple addition. In the meantime, if there is a duplicate, the later entry should override the previous one.
