### ISSUE TITLE
"Chord only" mode issue for Smart Punctuatio. 

### ISSUE THREAD

**Issue by ellieLitwack** [psoukie/zipchord#6]
Hello and thank you so much for developing this tool! I use it every day and really appreciate it.

As of 1.5.2, when Smart Punctuation is set to "chord only" mode, entering a punctuation character will also enter a backspace character if the cursor has been moved.

For example, if I type "foo bar", the resulting text is "foo bar". If I move my cursor back to the end of foo and type a period, the resulting text is "fo. bar".

As another exampl, if I type "Bob and Alice", go to another windo, come back, and enter a comma, the resulting text is "Bob and Alic,. 

As a third example, if I type "Hello world", then type a bang, then a space, the resulting text is "Hello world! ". If I realize I also want to add a "?", I would try to do so by hitting backspace and then "?". I would expect the resulting text to be "Hello World!?" but it ends up actually being "Hello World?".

**Comment by ellieLitwack** [comment]
I'm thinking that changing consecutive to true on Interrupt is the issue. This works fine for the purposes of entering chords but it causes this issue when trying to use smart punctuation. From my perspective as a user, the expected behavior is that after an interrupt, chords are treated as consecutive but smart punctuation is not.

**Comment by psoukie** [comment]
Thank you, Ellie!

I missed that my quick fix caused an issue with the punctuation.

I’ll have time to look at it tonight or tomorrow to fix this.

Thank you for the kind words and the detailed retro steps.

Best,

Pavel

On Oct 14, 2022, at 12:23 PM, Ellie Litwack ***@***.***> wrote:

﻿

Hello and thank you so much for developing this tool! I use it every day and really appreciate it.

As of 1.5.2, when Smart Punctuation is set to "chord only" mode, entering a punctuation character will also enter a backspace character if the cursor has been moved.

For example, if I type "foo bar", the resulting text is "foo bar". If I move my cursor back to the end of foo and type a period, the resulting text is "fo. bar".

As another exampl, if I type "Bob and Alice", go to another windo, come back, and enter a comma, the resulting text is "Bob and Alic,.

As a third example, if I type "Hello world", then type a bang, then a space, the resulting text is "Hello world! ". If I realize I also want to add a "?", I would try to do so by hitting backspace and then "?". I would expect the resulting text to be "Hello World!?" but it ends up actually being "Hello World?".

**Comment by ellieLitwack** [comment]
Hi Pavel! I just installed 1.6 and it works perfectly! Thank you so much for this software!
