### ISSUE TITLE
Chords not working

### ISSUE THREAD

**Issue by Tacocat263** [psoukie/zipchord#75]
**Describe the bug**
- A short description of the bug. some chords do not work
- What happens, and what do you expect to happen instead? if i do the possible or give chord for example (psbl and gv) it just doesn't do the chord

**Useful Details**
- Which settings do you have selected in the ZipChord settings? Default
- If the output is wrong, what is the sequence of keys pressed, the dictionary entry, and what text appears on the screen? psbl, shorthands english, psbl

**Comment by Imlk567** [comment]
update: nd does than instead of need

**Comment by psoukie** [comment]
Thank you for the report. If I understand correctly, this could be if the "Detection delay" (on Detection tab) is set too low, and it fires a chord when you are intending to use a shorthand.

*Chords* are triggered by pressing multiple keys at the same time, while *shorthands* by regular typing. 
- In the default chord dictionary, "dn" (`D+N` pressed briefly together) chord produces the word "than"
- The default shorthands dictionary has "nd" (`N` followed by `D` and then a space or punctuation) defined for "need"

This might not be answering the question or explaining the bug. In that case, could you please download the latest version (Alpha 4), turn on the "Log this session (debugging)" option on About tab, and type some text that shows the problem you are describing? When you re-open the ZipChord window, it will stop the debugging and will open a text file with a debug log where you can copy-paste the actual output of the typing at the top. If you could attach the file, it would help me see what is happening.

**Comment by psoukie** [comment]
Please let me know if you are still experiencing issues with the chord / shorthands recognition with the latest version or in the 2.0 release candidate. Thank you!
