### ISSUE TITLE
mirroring

### ISSUE THREAD

**Issue by jsampson45** [psoukie/zipchord#8]
I read something about mirroring to deal with different words having the same chord, but I have not been able to find it again. Has it been removed?

**Comment by psoukie** [comment]
I think you might be referring to my comment in this closed issue: https://github.com/psoukie/zipchord/issues/1

I don't know how intuitive or practical these "mirrored" chords might be for other people. Here is when I use them and what I mean by it. I sometimes use the mirroring when I want to make a chord for a frequent word easier to 'type' or if I want to avoid a conflict with another existing chord in a creative way. A made up example (I use similar logic in my chords based on Dvorak keyboard but I am adapting it to QWERTY keyboard):

Let's say my preferred chords for '**what**', '**which**', and '**where**' would be **WT**, **WC** and **WR.** Here, **WC** in particular is a bit difficult, so I switch the W key over to O (it's the "same" key for right hand). And to make it consistent, I'd switch this for all three, and go with **OT**, *OC* and *OR*. (So I mentally treat the key O as the W(H) sound in the chords for these words).

Again, this approach might be too idiosyncratic to be generally useful. Users can define the chords with whatever logic or system helps them remember the chords.

To simply avoid duplicates, often it will make more sense to add one more key into the chord or use an alternate key.
