### ISSUE TITLE
Allow special keys in chords

### ISSUE THREAD

**Issue by psoukie** [psoukie/zipchord#90]
Allow keys that do not have any printed output, such as Print Screen or F1 - F12, to be used as part of a chord.

This could be useful in situations when these keys are not in use (for example Print Screen rarely is in a meaningful way), but they can still represent another key in the chord to differentiate these chords.

Implementation:

- [X] Build support using special key notation
- [x] Option for bypassing the key's normal function

This issue was based on:

"... The feature on my former local version ... I got used to press a "_custom modifier key_" [like PrintScreen] ... because it doesn't cast or do anything."
_Originally posted by @lmendez5 in https://github.com/psoukie/zipchord/issues/24#issuecomment-1371532402_

**Comment by psoukie** [comment]
It is now possible to define these special keys to be detected and used in chords using a special notation that is used in the Keyboard and Language Settings under "All keys".

To include these, use `{special_key:symbol}` where the _special_key_ is an AutoHotkey code of the key (such as "F1" or "PrintScreen") and the _symbol_ is the character of how it's recognized in chord dictionaries (such as "|" or "*").

## Example
We want to recognize keys **F8** and **Print Screen** in chords. To do this, in this example we will choose to represent F8 in chord dictionaries as `*` (asterisk) and Print Screen as `|` (pipe). (Note that other characters that are not typed directly using unmodified keys and that are different from `{`,`}`, and `:` could be used also, such as `(` or `)` on default English keyboards.)

On a standard English keyboard, the "**All keys**" under **Locale settings** in the Keyboard and Language settings would be set as follows:
```
{F6:*}`1234567890{PrintScreen:|}-=qwertyuiop[]\asdfghjkl;'zxcvbnm,./`
```
(The order in which the keys are defined doesn't matter. We are just telling ZipChord that `F6` will masquerade as `*`)

And the entries in the chord dictionary could be, for example:
```
*s	Your Signature	F6 + S will output "Your Signature"
|df	dumbfounded	Triggered by chord PrintScreen + D + F
```

**Comment by psoukie** [comment]
Obviously, it would be more user-friendly if the keyboard layout "All keys" _and_ the shortcuts in chord dictionaries could both simply use `{F8}`.

Unless there's a big demand for this, I'm inclined to stick with the workaround (described in the example) of defining a single character as a stand-in.

**Comment by lmendez5** [comment]
Well well well well!! 
I have been playing with this feature... amazing! You know, I have running another ahk in parallel to do other stuff... like move my current window through my four monitors, maximizing current window, open programs, indeed, in Spanish we have double exclamation and question marks (¡! ¿?) etc. So, with this useful feature I can configurate my stuff as a chord!!! yeeeeahhh!!! like this:

`,m=+#{left}` for moving the current window, or `,k=^{Tab}` for moving around browser tabs, `,p=¿?{Left}` to put open and close question marks and move the cursor to the left to start writing a question! so, I am moving some shortcuts to Zipchord! well, for me now is ZipchordActions or ZipchordCuts... I don't know!!! hahahaha Well, I am still trying to figure out how to run a program, but I will play with some code to try it, but I think it could be possible.

So, I left this comment -what I think is a useful stuff- just in case someone found it interesting to improve performance and productivity... or maybe if you want to add examples to the User Manual... it is up to you!

Thank you and if you know how to run programs... 😬 haha 
See you! take care!!

**Comment by psoukie** [comment]
That's great to hear. For running programs -- sadly, the dictionary can only do whatever AutoHotkey allows to be included as keyboard entry -- and right now (to correctly support extended characters), unless there is a { brace in the output text it does not interpret something like `#r` as `Windows key` + `R`. 

Still, if you need to run an app, you could use Win key and R (open the Windows Run dialog), and then define a chord to produce `Notepad{Enter}` to run Notepad. (Defining `#rNotepad{Enter}` doesn't work because the word "Notepad" and Enter are executed quicker than the Run window opens.)

I think a tips and tricks section under the Discussions would be nice. (I didn't get around to it yet.)

**Comment by psoukie** [comment]
I'm closing this issue. I am also updating the comment, which should later go into the readme documentation or into tips/tricks in Discussions with a link from documentation.
